name: Robot Framework Reporter Demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: ppodgorsek/robot-framework:latest

      with:
        robot_tests_dir: TestCases